import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Navbar";
import { Cormorant_Garamond } from 'next/font/google';

const garamond = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['400', '600'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white flex`}
      >
        <Sidebar />
        <main className={`${garamond.className} ml-15 w-full h-screen overflow-y-auto p-6 scrollbar-hide`}>
          {children}
        </main>
      </body>
    </html>
  );
}
